// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0--rc2
// source: botjob.proto

package RmqProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   string           `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`
	PageId  string           `protobuf:"bytes,2,opt,name=PageId,proto3" json:"PageId,omitempty"`
	PageUrl string           `protobuf:"bytes,3,opt,name=PageUrl,proto3" json:"PageUrl,omitempty"`
	ToDo    []*BotJob_Action `protobuf:"bytes,4,rep,name=ToDo,proto3" json:"ToDo,omitempty"`
}

func (x *BotJob) Reset() {
	*x = BotJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_botjob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotJob) ProtoMessage() {}

func (x *BotJob) ProtoReflect() protoreflect.Message {
	mi := &file_botjob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotJob.ProtoReflect.Descriptor instead.
func (*BotJob) Descriptor() ([]byte, []int) {
	return file_botjob_proto_rawDescGZIP(), []int{0}
}

func (x *BotJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BotJob) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *BotJob) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *BotJob) GetToDo() []*BotJob_Action {
	if x != nil {
		return x.ToDo
	}
	return nil
}

type BotJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    string `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	PageId  string `protobuf:"bytes,2,opt,name=PageId,proto3" json:"PageId,omitempty"`
	PageUrl string `protobuf:"bytes,3,opt,name=PageUrl,proto3" json:"PageUrl,omitempty"`
	Status  bool   `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Hash    string `protobuf:"bytes,5,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *BotJobResponse) Reset() {
	*x = BotJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_botjob_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotJobResponse) ProtoMessage() {}

func (x *BotJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_botjob_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotJobResponse.ProtoReflect.Descriptor instead.
func (*BotJobResponse) Descriptor() ([]byte, []int) {
	return file_botjob_proto_rawDescGZIP(), []int{1}
}

func (x *BotJobResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BotJobResponse) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *BotJobResponse) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *BotJobResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *BotJobResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type BotJob_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screenshot   bool `protobuf:"varint,1,opt,name=Screenshot,proto3" json:"Screenshot,omitempty"`
	Availability bool `protobuf:"varint,2,opt,name=Availability,proto3" json:"Availability,omitempty"`
}

func (x *BotJob_Action) Reset() {
	*x = BotJob_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_botjob_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotJob_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotJob_Action) ProtoMessage() {}

func (x *BotJob_Action) ProtoReflect() protoreflect.Message {
	mi := &file_botjob_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotJob_Action.ProtoReflect.Descriptor instead.
func (*BotJob_Action) Descriptor() ([]byte, []int) {
	return file_botjob_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BotJob_Action) GetScreenshot() bool {
	if x != nil {
		return x.Screenshot
	}
	return false
}

func (x *BotJob_Action) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

var File_botjob_proto protoreflect.FileDescriptor

var file_botjob_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x74, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0xc5, 0x01, 0x0a, 0x06, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x14, 0x0a,
	0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a, 0x6f,
	0x62, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61,
	0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x04, 0x54, 0x6f, 0x44, 0x6f, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x74, 0x4a, 0x6f, 0x62, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x54, 0x6f, 0x44, 0x6f, 0x1a, 0x4c, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x82, 0x01, 0x0a, 0x0e, 0x42,
	0x6f, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_botjob_proto_rawDescOnce sync.Once
	file_botjob_proto_rawDescData = file_botjob_proto_rawDesc
)

func file_botjob_proto_rawDescGZIP() []byte {
	file_botjob_proto_rawDescOnce.Do(func() {
		file_botjob_proto_rawDescData = protoimpl.X.CompressGZIP(file_botjob_proto_rawDescData)
	})
	return file_botjob_proto_rawDescData
}

var file_botjob_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_botjob_proto_goTypes = []interface{}{
	(*BotJob)(nil),         // 0: pb.BotJob
	(*BotJobResponse)(nil), // 1: pb.BotJobResponse
	(*BotJob_Action)(nil),  // 2: pb.BotJob.Action
}
var file_botjob_proto_depIdxs = []int32{
	2, // 0: pb.BotJob.ToDo:type_name -> pb.BotJob.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_botjob_proto_init() }
func file_botjob_proto_init() {
	if File_botjob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_botjob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_botjob_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_botjob_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotJob_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_botjob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_botjob_proto_goTypes,
		DependencyIndexes: file_botjob_proto_depIdxs,
		MessageInfos:      file_botjob_proto_msgTypes,
	}.Build()
	File_botjob_proto = out.File
	file_botjob_proto_rawDesc = nil
	file_botjob_proto_goTypes = nil
	file_botjob_proto_depIdxs = nil
}
